AUDIO_SAMPLES_DIR = 'audio_samples'
AUDIO_SAMPLES_TIMESTAMPS_DIR = 'audio_samples_timestamps'
RECIPES_DIR = 'recipes'
EFFECTS_DIR = 'effects'

AUDIO_FILE = 'output'
TIMESTAMPS_FILE = 'timestamps'

PANEL_LED_PIN = 27
EFFECT_1_PIN = 22
EFFECT_2_PIN = 23
EFFECT_3_PIN = 24
BUTTON_PIN = 16
BUTTON_PULL_DOWN = False
RECIPE_LENGTH = 'length'
RECIPE_SAMPLES = 'samples'
RECIPE_SAMPLE_NAME = 'name'
RECIPE_SAMPLE_FREQUENCY = 'frequency_range'
RECIPE_SAMPLE_FREQUENCY_MIN = 'min'
RECIPE_SAMPLE_FREQUENCY_MAX = 'max'
TIMESTAMPS_START = 'start'
TIMESTAMPS_END = 'stop'